/**
 * @description This class is used to manage all batch jobs that implement the IBatchJob interface.
 *              It provides centralized methods to start, stop, and retrieve batch jobs,
 *              abstracting away the details of scheduling and job abortion.
 *              -----------------------------------------------------------------------------
 *              Developer            Date            Description
 *              -----------------------------------------------------------------------------
 *              Kenneth Houkjær      06/10/2025      Initial version.
 *              Kenneth Houkjær      06/10/2025      Updated for metadata-driven chaining and new features.
 *
 * @author Kenneth Houkjær
 * @date 06/10/2025
 */
public class BatchJobManager {
//   TODO: DELETE ME
}