/** TODO DELETE ME **/
/**
 * The NumberClientServiceTest class is responsible for testing the NumberClientService class.
 *  -----------------------------------------------------------------------------
 *  Developer            Date            Description
 *  -----------------------------------------------------------------------------
 *  Kenneth Houkjær         29/07/2025      Initial version
 *
 * @author Kenneth Houkjær
 * @date 29/07/2025
 */
@IsTest(IsParallel = true)
public class NumberClientServiceTest {

}